---
# Variables can be set from the shell: `DOCKERTAG=foo docker-compose build`
# or from a .env file. See docker-compose documentation for details
# Variable DOCKERUSER should be set to your dockerhub user
# Alternatively, use a docker registry url as the image name
version: '3.7'
services:
  ## Image runtime service
  ## This can be used to add volume mounts or pass environment variables
  ## Todo: make a service which can use the container interactively
  api:
    container_name: openface
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: "${DOCKERUSER}/openface:${DOCKERTAG}"
    ports:
      - "8000:8000"
    # develop: 
    #   watch: 
    #     - action : sync
    #       path : /opengaze/
    #       target : /opengaze/
    tty: true
    # volumes:
    #   - ./data:/tmp/openface
    environment:
      # DATA_MOUNT: "/tmp/openface"
      LC_ALL : C.UTF-8
      LANG : C.UTF-8
    # command: bash
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
  
...